name: Prometheus Bug Report
description: File a Prometheus bug report
title: "[Prometheus Bug]: "
labels: ["bug", "triage", "Prometheus"]
assignees:
  - spydmobile
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! By submitting this issue, you agree to follow our [Code of Conduct](https://firegrowthmodel.ca/pages/conduct.html)
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running (if your version is not listed, download the latest instead)?
      options:
        - (Release) 6.2.4
        - (Release) 6.2.3
        - (Release) 6.2.2
        - (Dev) 6.2.6.x
        - (Dev) 2021.12.03
    validations:
      required: true
  - type: dropdown
    id: windows
    attributes:
      label: What version of Windows are you seeing the problem on?
      multiple: true
      options:
        - Windows 7 32-bit
        - Windows 7 64-bit
        - Windows 10 32-bit
        - Windows 10 64-bit
        - Windows 11 
        - Other (indicate in "What happened" above)
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: approval
    attributes:
      label: Approvals Process
      description: All to be completed for bug fix
      options:
        - label: Testing For Issue
        - label: Executive Approval
        - label: Merge
