name: PSaaS Bug Report
description: File a bug report
title: "[PSaaS Bug]: "
labels: ["bug", "triage", "PSaaS"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running (if your version is not listed, download the latest instead)?
      options:
        - (Linux) 2021.11.xx
        - (Windows) 2021.12.xx
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: What component are you seeing the problem on?
      multiple: true
      options:
        - Builder
        - Manager
        - PSaaS Binary
        - JS Api
        - Documentation
        - Other (indicate in "What happened" above)
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://firegrowthmodel.com/conduct.html)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true