name: WISE Feature Request
description: Request a new feature in WISE
title: "[WISE FR]: "
labels: ["feature", "triage", "W.I.S.E"]
assignees:
  - spydmobile
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-is-needed
    attributes:
      label: What is needed?
      description: Also tell us, how you might imagine this is implemented!
      placeholder: Tell us what you want!
      value: "I would like a purple widget added to the about screen below the version number!"
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: How will this improve the project or tool?
      description: Proivide additional context.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://firegrowthmodel.ca/pages/conduct.html)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
